Let's say you take a trip with your friends or you live with your room mates in an appartment. In both cases, there are things that you buy for yourself and there are investments that are best shared as common goods.
At some point the trip is over or your room mates move out, so how to split those shared expenses?
Easy one might think, let's just split everything by the number of people, right? Well, in reality it's never so easy. There are two basic approaches to the problem: a common pool or calculate all interdependencies by use of matrixing.
Both approaches work and should get you to the same results but have different advantages and disadvantages.

## Pooling
Anyone with a basic education will come up with the idea of pooling, and there is a certain charm in its simplicity. The often implicit assumption is that the community has a common pool of resources and all expenses are calculated against this common pool - NOT between each member.

In [1]:
# Member expenses in total
A = 0
B = 1
C = 2

# number of members
n = 3

total = A + B + C
# the share of each member that needs to be paid to balance all
share = total/n

# debits and credits of members to community
balance_A = A - share
balance_B = B - share
balance_C = C - share

print(f"""
G -> A: {round(balance_A,2)}
G -> B: {round(balance_B,2)}
G -> C: {round(balance_C, 2)}""")


G -> A: -1.0
G -> B: 0.0
G -> C: 1.0


This approach will work well if all expenses etc. are done only with respect to the common pool, but will break down quickly if members have credits and debits amongst each other.
Also, it is important to note that actually implementing a common pool either by using a bank account or a sock with money in it is recommended, otherwise the temptation is great to include favors amongst members in the calculation, which will overcomplicate the calculation quickly.

Note that this approach is common amongst larger organisations where the additinal overhead of maintaining a common pool is justified.

## Matrixing

The idea here is that, sure, all expenses should be shared in the end, but there is no need to maintain a common pool and no need to exclude private favours between members to calculate the balance between each member.
So, the only thing needed for this is to note down all expenses by each member over the course of time that should be shared in the end. This has the clear advantage of reducing the bureaucratic overhead to a bare minimum but also means a slightly more complex calculation at the end.

In [2]:
from numpy import zeros, fill_diagonal

# Member expenses in total
A = 0
B = 1
C = 2

# number of members
n = 3

M = zeros((n, n))

M[0:n,0] = A * 1/n
M[0:n,1] = B * 1/n
M[0:n,2] = C * 1/n

fill_diagonal(M, 0)

print(M)

T = M.transpose()

A2B = T[1,0] - M[1,0]
A2C = T[2,0] - M[2,0]
B2C = T[2,1] - M[2,1]

print(f"""
A -> B: {round(A2B,2)}
A -> C: {round(A2C,2)}
B -> C: {round(B2C, 2)}""")

[[ 0.          0.33333333  0.66666667]
 [ 0.          0.          0.66666667]
 [ 0.          0.33333333  0.        ]]

A -> B: 0.33
A -> C: 0.67
B -> C: 0.33


Clearly, B and C have no obligations to A, so A clearly must pay 1/3 of both expenses without compensation.
For B and C it's not so simple since C also needs to pay 1/3 of B's expenses, which is summed with what B owes C, which is exactly the amount of money that A owes B. The amount A -> B -> C is exactly the amount missing between A -> C for a full 1, which is also the amount calculated by pooling much more easily.
It is obvious that matrixing is more daunting and complex (but not really complicated) than pooling - except when it isn't. With matrixing it is possible to include each and every credit amongst members without making things more complicated, while it is impossible to include those in the pooling approach. If there are many such favours with a pooling approach, it may become necessary to additionally use matrixing in the end - so why not use it in the first place?

Note that this means that there is one unnecessary transaction that could be eliminated.

with real numbers from my appartment:

In [3]:
from numpy import zeros

# Member expenses in total

A = 14.98
B = 16.65 
C = 33.14

# number of members
n = 3

M = zeros((n, n))

M[0:n,0] = A * 1/n
M[0:n,1] = B * 1/n
M[0:n,2] = C * 1/n

M[2,0:2] += 5  # things like this aren't possible with pooling

fill_diagonal(M, 0)

print(M)

T = M.transpose()

A2B = T[1,0] - M[1,0]
A2C = T[2,0] - M[2,0]
B2C = T[2,1] - M[2,1]

print(f"""
A -> B: {round(A2B,2)}
A -> C: {round(A2C,2)}
B -> C: {round(B2C, 2)}""")

[[  0.           5.55        11.04666667]
 [  4.99333333   0.          11.04666667]
 [  9.99333333  10.55         0.        ]]

A -> B: 0.56
A -> C: 1.05
B -> C: 0.5


In [34]:
from numpy import zeros, fill_diagonal

# Totalausgaben 2018-08-03
A = 16
L = 2.25+3
S = 0.86+1.95+2.15+3+2.75+3.5
V = 0

# Anzahl Mitbewohner
n = 4

M = zeros((n, n))


M[:,0] = A * 1/n
M[:,1] = L * 1/n # Lars
M[:,2] = S * 1/n # Sarah
M[:,3] = V * 1/n # Verena

fill_diagonal(M, 0)

M[1,0] += 54.80 / 3 # Glastisch
M[3,0] += 54.80 / 3 # Glastisch
M[2,0] += 17 # Essen

print(M)

T = M.transpose()

L2A = T[1,0] - M[1,0]
S2A = T[2,0] - M[2,0]
V2A = T[3,0] - M[3,0]
print("L, S, V -> A")
print(L2A, S2A, V2A)

V2L = T[3,1] - M[3,1]
V2S = T[3,2] - M[3,2]
print("V -> L, S")
print(V2L, V2S)

L2S = T[1,2] - M[1,2]
print("L -> S")
print(L2S)

[[ 0.          1.3125      3.5525      0.        ]
 [22.26666667  0.          3.5525      0.        ]
 [21.          1.3125      0.          0.        ]
 [22.26666667  1.3125      3.5525      0.        ]]
L, S, V -> A
-20.954166666666666 -17.447499999999998 -22.266666666666666
V -> L, S
-1.3125 -3.5525
L -> S
-2.24
